[workspace]
resolver = "2"

members = ["day-*"]

[workspace.dependencies]
anyhow = "1.0.75"
nom = "7.1.3"
regex = "1.10.2"
indicatif = "0.17.7"
nom-supreme = "0.8.0"
itertools = "0.12.0"
rayon = "1.8.0"
petgraph = "0.6.4"
glam = "0.24.2"